spring:
  application:
    name: training
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/smart_access
    username: danek
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        format_sql: true
